#' @title Pseudoausencias en base a las presencias, con radio de exclusión / Pseudoabsences Based on Presences, with Exclusion Radius
#'
#' @description
#' Genera pseudoausencias (ausencias simuladas) balanceadas en proporción 1:1
#' para modelos de nicho ecológico y distribución de especies. La función
#' aplica un radio de exclusión espacial alrededor de las presencias reales
#' para evitar seleccionar pseudoausencias en áreas donde es biológicamente
#' improbable que la especie esté ausente debido a la proximidad con
#' registros confirmados.
#' /
#' Generates balanced pseudoabsences (simulated absences) in 1:1 proportion
#' for ecological niche modeling and species distribution modeling. The function
#' applies a spatial exclusion radius around real presences to avoid selecting
#' pseudoabsences in areas where it is biologically unlikely for the species
#' to be absent due to proximity to confirmed records.
#'
#' @param Resultados Lista de data frames con presencias por especie, típicamente
#'   generada por la función `Presencias_Sf_Sin_Na()`. Cada data frame debe contener:
#'   - Columnas `longitud` y `latitud` con coordenadas en grados decimales
#'   - Columna `especievalida` con el identificador de la especie
#'   - Variables ambientales extraídas del raster para cada ubicación
#'   - Columna `Presencia` con valor `1` para todos los registros
#'   /
#'   List of data frames with presences by species, typically generated by
#'   the `Presencias_Sf_Sin_Na()` function. Each data frame must contain:
#'   - `longitud` and `latitud` columns with coordinates in decimal degrees
#'   - `especievalida` column with species identifier
#'   - Environmental variables extracted from raster for each location
#'   - `Presencia` column with value `1` for all records
#'
#' @param Raster_CRS_Referencia Objeto `SpatRaster` de terra con las variables
#'   ambientales ya proyectadas al sistema de coordenadas de trabajo. Este
#'   raster define:
#'   - La resolución espacial para la selección de pseudoausencias
#'   - La extensión geográfica disponible para seleccionar pseudoausencias
#'   - Los valores ambientales que serán extraídos para las pseudoausencias
#'   /
#'   `SpatRaster` object from terra with environmental variables already
#'   projected to the working coordinate system. This raster defines:
#'   - The spatial resolution for pseudoabsence selection
#'   - The geographic extent available for pseudoabsence selection
#'   - Environmental values that will be extracted for pseudoabsences
#'
#' @param Objeto_CRS_referencia Objeto espacial (`sf`, `sfc` o `SpatVector`)
#'   que define el sistema de coordenadas de referencia final para los datos
#'   de salida. También puede ser un CRS en formato EPSG (ej. `4326` o
#'   `"EPSG:4326"`). Todos los datos serán transformados a este CRS.
#'   /
#'   Spatial object (`sf`, `sfc` or `SpatVector`) defining the final
#'   coordinate reference system for output data. Can also be a CRS in EPSG
#'   format (e.g., `4326` or `"EPSG:4326"`). All data will be transformed
#'   to this CRS.
#'
#' @returns
#' Una lista invisible (no se imprime automáticamente) de objetos `sf`, uno por
#' especie, con las siguientes características:
#' * **Presencias originales**: Todos los registros de presencia originales
#' * **Pseudoausencias**: Número igual al de presencias (proporción 1:1)
#' * **Variables ambientales**: Todos los valores del raster en cada ubicación
#' * **Variable respuesta**: Columna `Presence` con `1` (presencia) y `0` (pseudoausencia)
#' * **Identificación**: Columna `especievalida` con el nombre de la especie
#' * **Geometría**: Puntos en el CRS especificado por `Objeto_CRS_referencia`
#' * **Exclusión espacial**: No se seleccionan pseudoausencias dentro de un radio de
#'   0.1 grados (~11 km en el ecuador) o 10 km (en proyección métrica) de las presencias
#'
#' La lista puede ser asignada a un objeto y luego accedida por nombre de especie.
#' /
#' An invisible list (not automatically printed) of `sf` objects, one per
#' species, with the following features:
#' * **Original presences**: All original presence records
#' * **Pseudoabsences**: Equal number to presences (1:1 proportion)
#' * **Environmental variables**: All raster values at each location
#' * **Response variable**: `Presence` column with `1` (presence) and `0` (pseudoabsence)
#' * **Identification**: `especievalida` column with species name
#' * **Geometry**: Points in the CRS specified by `Objeto_CRS_referencia`
#' * **Spatial exclusion**: No pseudoabsences selected within a radius of
#'   0.1 degrees (~11 km at equator) or 10 km (in metric projection) from presences
#'
#' The list can be assigned to an object and then accessed by species name.
#'
#' @details
#' La función implementa el siguiente algoritmo para cada especie:
#'
#' 1. **Preparación de datos**:
#'    - Extrae coordenadas de las presencias
#'    - Convierte presencias a objeto espacial en el CRS del raster
#'    - Identifica celdas del raster que contienen presencias
#'
#' 2. **Definición de área de exclusión**:
#'    - Calcula un radio de exclusión basado en el sistema de coordenadas:
#'      - Para CRS geográficos (grados): 0.1 grados (~11 km)
#'      - Para CRS proyectados (metros): 10,000 metros (10 km)
#'    - Crea buffers alrededor de cada presencia usando el radio apropiado
#'
#' 3. **Selección de pseudoausencias**:
#'    - Genera todas las celdas del raster dentro de su extensión
#'    - Elimina celdas que contienen presencias reales
#'    - Elimina celdas dentro del área de exclusión (buffers)
#'    - Selecciona aleatoriamente un número de celdas igual al de presencias
#'
#' 4. **Extracción de valores ambientales**:
#'    - Extrae valores de todas las capas del raster para las pseudoausencias
#'    - Combina con valores de las presencias
#'
#' 5. **Transformación y estructuración**:
#'    - Asigna valores de presencia (1) y pseudoausencia (0)
#'    - Transforma a CRS final especificado
#'    - Convierte a objeto `sf` con geometrías puntuales
#'    - Asegura que todas las especies tengan estructura consistente
#'
#' 6. **Validación**:
#'    - Verifica que haya suficientes celdas disponibles para pseudoausencias
#'    - Emite advertencias para especies con pocas celdas disponibles
#'    - Excluye especies que no pueden generar pseudoausencias balanceadas
#'
#' /
#' The function implements the following algorithm for each species:
#'
#' 1. **Data preparation**:
#'    - Extracts coordinates from presences
#'    - Converts presences to spatial object in raster's CRS
#'    - Identifies raster cells containing presences
#'
#' 2. **Exclusion area definition**:
#'    - Calculates exclusion radius based on coordinate system:
#'      - For geographic CRS (degrees): 0.1 degrees (~11 km)
#'      - For projected CRS (meters): 10,000 meters (10 km)
#'    - Creates buffers around each presence using appropriate radius
#'
#' 3. **Pseudoabsence selection**:
#'    - Generates all raster cells within the raster extent
#'    - Removes cells containing real presences
#'    - Removes cells within exclusion area (buffers)
#'    - Randomly selects number of cells equal to presences
#'
#' 4. **Environmental value extraction**:
#'    - Extracts values from all raster layers for pseudoabsences
#'    - Combines with presence values
#'
#' 5. **Transformation and structuring**:
#'    - Assigns presence (1) and pseudoabsence (0) values
#'    - Transforms to final specified CRS
#'    - Converts to `sf` object with point geometries
#'    - Ensures all species have consistent structure
#'
#' 6. **Validation**:
#'    - Verifies sufficient cells available for pseudoabsences
#'    - Issues warnings for species with few available cells
#'    - Excludes species that cannot generate balanced pseudoabsences
#'
#' @note
#' * La proporción 1:1 (presencia:pseudoausencia) es común en modelado de
#'   distribución de especies, pero puede ajustarse manualmente si es necesario.
#' * El radio de exclusión (0.1° o 10 km) está basado en recomendaciones
#'   estándar para evitar sobreajuste espacial en los modelos.
#' * Las pseudoausencias se seleccionan aleatoriamente, por lo que diferentes
#'   ejecuciones pueden producir resultados distintos. Use `set.seed()` para
#'   reproducibilidad.
#' * La función maneja automáticamente la diferencia entre sistemas de
#'   coordenadas geográficas (grados) y proyectadas (metros).
#' * Especies con muchas presencias y/o raster de alta resolución pueden
#'   requerir tiempo de procesamiento significativo.
#' /
#' * The 1:1 proportion (presence:pseudoabsence) is common in species
#'   distribution modeling but can be manually adjusted if needed.
#' * The exclusion radius (0.1° or 10 km) is based on standard recommendations
#'   to avoid spatial overfitting in models.
#' * Pseudoabsences are randomly selected, so different runs may produce
#'   different results. Use `set.seed()` for reproducibility.
#' * The function automatically handles differences between geographic
#'   (degrees) and projected (meters) coordinate systems.
#' * Species with many presences and/or high-resolution rasters may require
#'   significant processing time.
#'
#' @section Advertencias/Warnings:
#' * **Disponibilidad de celdas**: Si hay más presencias que celdas disponibles
#'   después de aplicar la exclusión, la función reducirá proporcionalmente
#'   las pseudoausencias y emitirá una advertencia.
#' * **Área de estudio pequeña**: En áreas geográficas pequeñas o con muchas
#'   presencias, puede haber muy pocas celdas disponibles para pseudoausencias.
#' * **Resolución del raster**: Rasters de muy alta resolución (celdas pequeñas)
#'   pueden hacer que el proceso de exclusión sea muy estricto, limitando las
#'   opciones de pseudoausencias.
#' * **Transformación de CRS**: La doble transformación (presencias → raster CRS →
#'   CRS final) puede introducir pequeñas imprecisiones en las coordenadas.
#' * **Memoria**: Para rasters grandes con muchas especies, el proceso puede
#'   consumir mucha memoria al generar todas las celdas posibles.
#' /
#' * **Cell availability**: If there are more presences than available cells
#'   after applying exclusion, the function will proportionally reduce
#'   pseudoabsences and issue a warning.
#' * **Small study area**: In small geographic areas or with many presences,
#'   there may be very few cells available for pseudoabsences.
#' * **Raster resolution**: Very high-resolution rasters (small cells) can
#'   make the exclusion process very strict, limiting pseudoabsence options.
#' * **CRS transformation**: Double transformation (presences → raster CRS →
#'   final CRS) may introduce small inaccuracies in coordinates.
#' * **Memory**: For large rasters with many species, the process may consume
#'   significant memory when generating all possible cells.
#'
#' @examples
#' \dontrun{
#' # Ejemplo 1: Uso básico después de generar presencias
#' # Example 1: Basic usage after generating presences
#'
#' # Primero generar presencias sin NA
#' # First generate presences without NA
#' Subsets_Df_Presencias_Sin_Na <- Presencias_Sf_Sin_Na(
#'   Data_Sf = datos_presencia_sf,
#'   raster_referencia_reproyectado = raster_ambiental,
#'   Especie_Valida = "especie"
#' )
#'
#' # Luego generar pseudoausencias balanceadas
#' # Then generate balanced pseudoabsences
#' pseudoausencias <- Simular_Pseudoausencias_Sin_NA(
#'   Resultados = Subsets_Df_Presencias_Sin_Na,
#'   Raster_CRS_Referencia = Raster_Tif_reproyectado,
#'   Objeto_CRS_referencia = Oax_sf
#' )
#'
#' # Acceder a datos de una especie específica
#' # Access data for a specific species
#' especie_1 <- pseudoausencias[["NombreEspecie1"]]
#'
#' # Verificar proporción presencia/pseudoausencia
#' # Check presence/pseudoabsence proportion
#' table(especie_1$Presence)
#'
#' # Visualizar resultados
#' # Visualize results
#' plot(st_geometry(especie_1),
#'      col = ifelse(especie_1$Presence == 1, "red", "blue"),
#'      pch = 16, cex = 0.7)
#'
#' # Ejemplo 2: Con semilla para reproducibilidad
#' # Example 2: With seed for reproducibility
#' set.seed(123)
#' pseudoausencias_repro <- Simular_Pseudoausencias_Sin_NA(
#'   Resultados = Subsets_Df_Presencias_Sin_Na,
#'   Raster_CRS_Referencia = raster_ambiental,
#'   Objeto_CRS_referencia = 4326  # CRS como número EPSG / CRS as EPSG number
#' )
#'
#' # Ejemplo 3: Análisis de todas las especies
#' # Example 3: Analysis of all species
#' resumen_especies <- data.frame(
#'   Especie = names(pseudoausencias),
#'   n_Presencias = sapply(pseudoausencias, function(x) sum(x$Presence == 1)),
#'   n_Pseudoausencias = sapply(pseudoausencias, function(x) sum(x$Presence == 0))
#' )
#' print(resumen_especies)
#' }
#'
#' @importFrom terra extract crs vect cells as.points rast
#' @importFrom sf st_as_sf st_transform st_buffer st_crs st_coordinates
#' @importFrom dplyr bind_rows sample_n
#' @importFrom stats runif
#'
#' @seealso
#' * [Presencias_Sf_Sin_Na()] para generar los datos de entrada requeridos
#'   / to generate required input data
#' * [terra::extract()] para extraer valores de raster en puntos
#'   / to extract raster values at points
#' * [sf::st_buffer()] para crear áreas de exclusión alrededor de puntos
#'   / to create exclusion areas around points
#' * [set.seed()] para establecer semilla y resultados reproducibles
#'   / to set seed for reproducible results
#'
#' @export
Simulate_Pseudoabsences_No_NA_List_Df <- function(Resultados, Raster_CRS_Referencia, Objeto_CRS_referencia){
  resultados_finales_List <- list()
  for (i in names(Resultados)) {
    Especie_En_Procesamiento_Df <- Resultados[[i]]
    Presencias_Sin_Na_sf <- Especie_En_Procesamiento_Df %>%
      sf::st_as_sf(coords = c("longitud", "latitud"),
                   crs = 4326) %>%
      sf::st_transform(sf::st_crs(Raster_CRS_Referencia))
    if (sf::st_is_longlat(Presencias_Sin_Na_sf)) {
      Radio_Presencia <- 0.1
      Poligono_Radio <- Presencias_Sin_Na_sf %>%
        sf::st_buffer(dist = Radio_Presencia) %>%
        sf::st_union() %>%
        sf::st_as_sf()
    } else {
      Radio_Presencia <- 10000
      Poligono_Radio <- Presencias_Sin_Na_sf %>%
        sf::st_buffer(dist = Radio_Presencia) %>%
        sf::st_union() %>%
        sf::st_as_sf()
    }
    Celda_Raster_Con_Presencia <- terra::cellFromXY(Raster_CRS_Referencia[[1]], sf::st_coordinates(Presencias_Sin_Na_sf))
    Celda_Raster_Sin_Na <- which(!is.na(terra::values(Raster_CRS_Referencia[[1]])))
    Celdas_Disponibles_Para_Pseudoausencias <- setdiff(Celda_Raster_Sin_Na, Celda_Raster_Con_Presencia)
    if (length(Celdas_Disponibles_Para_Pseudoausencias) == 0) {
      stop("ERROR: No hay celdas disponibles (todas tienen presencias o son NA)")
    }
    n_Presencias <- nrow(Presencias_Sin_Na_sf)
    n_ausencias_posibles <- min(n_Presencias, length(Celdas_Disponibles_Para_Pseudoausencias))
    Pseudoausencias_Aleatorias_En_CDPP <- sample(Celdas_Disponibles_Para_Pseudoausencias, n_ausencias_posibles, replace = FALSE)
    Coordenadas_Raster <- terra::xyFromCell(Raster_CRS_Referencia[[1]], Pseudoausencias_Aleatorias_En_CDPP)
    Coordenadas_Raster_Sf <- sf::st_as_sf(
      data.frame(x = Coordenadas_Raster[,1], y = Coordenadas_Raster[,2]),
      coords = c("x", "y"),
      crs = terra::crs(Raster_CRS_Referencia)
    )
    Spavector_Variables_Ambientales_Pseudoausencias <- terra::vect(Coordenadas_Raster_Sf)
    Variables_Ambientales_Pseudoausencias <- terra::extract(
      Raster_CRS_Referencia,
      Spavector_Variables_Ambientales_Pseudoausencias,
      method = 'simple',
      ID = FALSE,
      bind = FALSE
    )
    Exclusion_Radio_Presencias <- sf::st_intersects(Coordenadas_Raster_Sf, Poligono_Radio, sparse = FALSE)
    Variables_Ambientales_Pseudoausencias$Exclusion_Radio_Presencias <- as.numeric(Exclusion_Radio_Presencias[,1])
    Variables_Ambientales_Pseudoausencias_Df <- as.data.frame(Variables_Ambientales_Pseudoausencias)
    Variables_Ambientales_Pseudoausencias_Df$Presence <- ifelse(Variables_Ambientales_Pseudoausencias_Df$Exclusion_Radio_Presencias == 1, NA, 0)
    Nombre_EspecieValida <- unique(Especie_En_Procesamiento_Df$especievalida)
    Variables_Ambientales_Pseudoausencias_Df <- Variables_Ambientales_Pseudoausencias_Df %>%
      dplyr::mutate(
        especievalida = Nombre_EspecieValida,
        x = sf::st_coordinates(Coordenadas_Raster_Sf)[, "X"],
        y = sf::st_coordinates(Coordenadas_Raster_Sf)[, "Y"]
      ) %>%
      dplyr::select(especievalida, everything())
    Variables_Ambientales_Pseudoausencias_Df_Fuera_Radio <- Variables_Ambientales_Pseudoausencias_Df %>%
      dplyr::filter(Presence == 0)
    Raster_Nombre_Variables <- c("CarbonStock_05cmdepth_Mg_x_ha", "EvapoTransp")
    Variables_Ambientales_Pseudoausencias_Sin_Na <- Variables_Ambientales_Pseudoausencias_Df_Fuera_Radio %>%
      dplyr::filter(
        dplyr::if_all(
          dplyr::all_of(Raster_Nombre_Variables),
          ~ !is.na(.)
        )
      )
    if (inherits(Especie_En_Procesamiento_Df, "SpatialPointsDataFrame")) {
      Especie_En_Procesamiento_Df <- as.data.frame(Especie_En_Procesamiento_Df)
    }
    Datos_Pseudoausencias_Para_Fusion <- Especie_En_Procesamiento_Df %>%
      dplyr::select(especievalida, all_of(Raster_Nombre_Variables), longitud, latitud) %>%
      dplyr::mutate(
        ID = dplyr::row_number(),
        Presence = 1,
        x = longitud,
        y = latitud
      ) %>%
      dplyr::select(-longitud, -latitud)
    Datos_Ausencias_Para_Fusion <- Variables_Ambientales_Pseudoausencias_Sin_Na %>%
      dplyr::select(especievalida, all_of(Raster_Nombre_Variables), x, y) %>%
      dplyr::mutate(
        ID = dplyr::row_number() + nrow(Datos_Pseudoausencias_Para_Fusion),
        Presence = 0
      )
    Datos_Presencias_Ausencias_Juntos_Df <- dplyr::bind_rows(Datos_Pseudoausencias_Para_Fusion, Datos_Ausencias_Para_Fusion)
    Datos_Presencias_Ausencias_Juntos_Df_To_Sf <- Datos_Presencias_Ausencias_Juntos_Df %>%
      sf::st_as_sf(coords = c("x", "y"), crs = terra::crs(Raster_CRS_Referencia)) %>%
      sf::st_transform(sf::st_crs(Objeto_CRS_referencia))
    resultados_finales_List[[i]] <- Datos_Presencias_Ausencias_Juntos_Df_To_Sf
  }
  return(invisible(resultados_finales_List))
}
